version: '3'
services:
  app:
    build: ./docker/app
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      # Docker Desktopを使う場合以下でDISPLAY設定が出来る
      # - DISPLAY=host.docker.internal:0

    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
      - ./app:/home/docker/app